export const portalData = {
  refs: [
    { ref: '/about', text: 'portal' },
    { ref: '/schedule', text: 'news' },
    { ref: '/', text: 'about' },
    { ref: '/', text: 'applicants' },
    { ref: '/', text: 'students' },
    { ref: '/', text: 'science' },
    { ref: '/', text: 'contacts' },
    { ref: '/', text: 'media' },
  ],
  instituteCards: [
    { title: 'card1' },
    { title: 'card2' },
    { title: 'card3' },
    { title: 'card4' },
    { title: 'card5' },
    { title: 'card6' },
    { title: 'card7' },
    { title: 'card8' },
    { title: 'card9' },
    { title: 'card10' },
    { title: 'card11' },
    { title: 'card12' },
  ],
  contacts: {
    phoneTrans: 'phone',
    phone: '8-800-777-77-77',
    emailTrans: 'email',
    email: 'student@tltsu.ru',
    websiteTrans: 'website',
    website: 'tltsu.ru',
  },
  name: 'name',
}
